# Generated by Django 4.2.4 on 2023-08-07 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0002_alter_categoria_descricao_alter_categoria_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto_nome', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('descricao', models.TextField(blank=True, max_length=500)),
                ('preco', models.FloatField()),
                ('foto', models.ImageField(blank=True, upload_to='photos/products')),
                ('estoque', models.IntegerField()),
                ('avaliavel', models.BooleanField(default=True)),
                ('criado_date', models.DateTimeField(auto_now_add=True)),
                ('modificado_date', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categoria.categoria')),
            ],
        ),
    ]
