# Generated by Django 4.2.4 on 2023-08-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'verbose_name': 'produto', 'verbose_name_plural': 'produtos'},
        ),
        migrations.AlterField(
            model_name='produto',
            name='foto',
            field=models.ImageField(upload_to='photos/produtos'),
        ),
    ]
